version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=hrapp;Username=postgres;Password=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - Jwt__Key=your_secret_key_here_make_it_long_and_secure
      - Jwt__Issuer=hr_client_management
      - Jwt__Audience=hr_client_users
      - ASPNETCORE_ENVIRONMENT=Production

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hrapp
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


